on:
  push:
  pull_request:
  schedule:
    - cron: 0 0 * * 2

name: Build

env:
  RUSTFLAGS: '--deny warnings'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly, 1.36.0]
        TARGET:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - arm-unknown-linux-gnueabi # Raspberry Pi 1
          - armv7-unknown-linux-gnueabihf # Raspberry Pi 2, 3, etc
          # Bare metal
          - thumbv6m-none-eabi
          - thumbv7em-none-eabi
          - thumbv7em-none-eabihf
          - thumbv7m-none-eabi

        include:
          # Test nightly but don't fail
          - rust: nightly
            experimental: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.TARGET }}
          override: true

      - name: Checkout CI scripts
        uses: actions/checkout@v2
        with:
          repository: 'eldruin/rust-driver-ci-scripts'
          ref: 'master'
          path: 'ci'

      - run: ./ci/patch-no-std.sh
        if: ${{ ! contains(matrix.TARGET, 'x86_64') }}

      - name: Patch bench dependencies incompatible with MSRV
        if: matrix.rust == '1.36.0'
        run: |
          sed -i "s/fnv/#fnv/g" Cargo.toml
          sed -i "s/fnv/#fnv/g" comparison/Cargo.toml
          sed -i "s/metrohash/#metrohash/g" Cargo.toml
          sed -i "s/metrohash/#metrohash/g" comparison/Cargo.toml
          sed -i "s/twox-hash/#twox-hash/g" Cargo.toml
          sed -i "s/twox-hash/#twox-hash/g" comparison/Cargo.toml

      - name: Build workspace
        if: matrix.rust != '1.36.0' && matrix.TARGET == 'x86_64-unknown-linux-gnu'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=${{ matrix.TARGET }} --workspace

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=${{ matrix.TARGET }}

      - name: Build MSRV comparison
        if: matrix.rust == '1.36.0' && matrix.TARGET == 'x86_64-unknown-linux-gnu'
        working-directory: ./comparison
        run: cargo build --target=${{ matrix.TARGET }}

  checks:
    name: Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta]
        TARGET:
          - x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.TARGET }}
          override: true
          components: rustfmt

      - name: Doc
        uses: actions-rs/cargo@v1
        with:
          command: doc

      - name: Formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.42.0]
        TARGET:
          - x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.TARGET }}
          override: true
          components: clippy

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clippy comparison
        working-directory: ./comparison
        run:  cargo clippy

  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly, 1.36.0]
        TARGET: [x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl]
        include:
          - rust: nightly
            experimental: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.TARGET }}
          override: true

      - name: Patch bench dependencies incompatible with MSRV
        if: matrix.rust == '1.36.0'
        run: |
          sed -i "s/fnv/#fnv/g" Cargo.toml
          sed -i "s/fnv/#fnv/g" comparison/Cargo.toml
          sed -i "s/metrohash/#metrohash/g" Cargo.toml
          sed -i "s/metrohash/#metrohash/g" comparison/Cargo.toml
          sed -i "s/twox-hash/#twox-hash/g" Cargo.toml
          sed -i "s/twox-hash/#twox-hash/g" comparison/Cargo.toml

      - name: Test
        if: matrix.rust != '1.36.0' && matrix.TARGET != 'x86_64-unknown-linux-musl' # musl-gcc is not installed
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target=${{ matrix.TARGET }} --workspace

      - name: Test MSRV
        if: matrix.rust == '1.36.0' || matrix.TARGET == 'x86_64-unknown-linux-musl'
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target=${{ matrix.TARGET }}

      - name: Test MSRV comparison
        if: matrix.rust == '1.36.0' && matrix.TARGET != 'x86_64-unknown-linux-musl' # musl-gcc is not installed
        working-directory: ./comparison
        run: |
          cargo test --target=${{ matrix.TARGET }}

      - name: Build examples
        uses: actions-rs/cargo@v1
        if: contains(matrix.TARGET, 'x86_64')
        with:
          command: build
          args: --target=${{ matrix.TARGET }} --examples

  comparison-test:
    name: Comparison
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Compile benchmarks
        working-directory: ./comparison
        run: cargo bench --benches --no-run

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '--workspace --out Lcov -- --test-threads 1'

      - name: upload to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './lcov.info'